import React from "react";
import { useNavigate } from "react-router-dom";
import styles from "./style.module.scss";
import pic3 from "../../../assets/img/pic_3.png";
import pic4 from "../../../assets/img/pic_4.png";
import fbLogo from "../../../assets/icon/facebook_logo.png";
import googoleLogo from "../../../assets/icon/google_logo.png";
import instagramLogo from "../../../assets/icon/instagram_logo.png";
import tiktokLogo from "../../../assets/icon/tiktok_logo.png";
import registerPic from "../../../assets/img/register_pic.png";

const Intro = () => {
  const navigate = useNavigate();

  const handleLoginClick = () => {
    navigate("/login-form");
  };

  const handleSignUpClick = () => {
    navigate("/register");
  };

  return (
    <div className={styles.introContainer}>
      <div className={styles.introBackground}>
        <div className={styles.introContent}>
          <h2>About Us</h2>
          <p>Welcome to PersFash, your personalized fashion consultant powered by advanced technology.</p>
          <p>We are dedicated to helping you express your unique style effortlessly.</p>
          <p>By setting up your profile on PersFash, our algorithm analyzes your fashion preferences and provides tailored recommendations that suit your personality, body shape, and lifestyle.</p>
        </div>
      </div>

      <div className={styles.space}></div>

      <div className={styles.secondContent}>
        <div className={styles.secondContentText}>
          {/* <h2>What can we do?</h2>
          <p>Just know that I would die for you</p>
          <p>Baby, I would die for you, yeah</p> */}
        </div>
      </div>

      <div className={styles.thirdContent}>
        <div
          className={styles.card}
          style={{ backgroundImage: `url(${pic3})` }}
        >
          <div className={styles.cardTitle}>
            <h2>Free Package</h2>
          </div>
          <div className={styles.cardText}>
            <p>
            This package is designed for users who want to experience the basic features of PersFash. 
            The system will suggest 1-15 fashion products daily from Shopee stores based on your personal style. 
            These suggestions are generated by an algorithm, analyzing information from the Profile Set-up you provided.
            With the Free package, you’ll receive daily fashion recommendations that match your style and current trends, making it easy to choose fashion items without having to search on your own.
            </p>
          </div>
        </div>
        <div
          className={styles.card}
          style={{ backgroundImage: `url(${pic4})` }}
        >
          <div className={styles.cardTitle}>
            <h2>
              {/* Consulting <span className={styles.experts}>with experts</span> */}
              Premium Package
            </h2>
          </div>
          <div className={styles.cardText}>
            <p>
            For those looking for a more comprehensive personal fashion consulting experience, 
            the Premium package includes all the features of the Free package, 
            plus access to the personal wardrobe management tool. 
            In addition to receiving 1-15 daily fashion product suggestions from Shopee, 
            you can also save your favorite items, track the quantity and types of clothing in your wardrobe. 
            This tool helps you easily manage outfits, optimizing your personal style while avoiding duplicate purchases. 
            It’s the perfect option for customers who want to professionally build and manage their own fashion style.
            </p>
          </div>
        </div>
      </div>

      <div className={styles.registerSection}>
        <div
          className={styles.registerImage}
          style={{ backgroundImage: `url(${registerPic})` }}
        >
          <h2>Become a member now</h2>
        </div>

        <div className={styles.registerForm}>
          <h2>Create Account</h2>
          <div className={styles.socialButtons}>
            <img src={googoleLogo} alt="Google" onClick={handleLoginClick} />
            {/* <img src={instagramLogo} alt="Instagram" /> */}
            {/* <img src={tiktokLogo} alt="TikTok" /> */}
            <div className={styles.moreButton} onClick={handleLoginClick}>+</div>
          </div>
          <button className={styles.signUpButton} onClick={handleSignUpClick}>Sign up</button>
          <div className={styles.separator}></div>
          <p>Already have an account?</p>
          <button className={styles.logInButton} onClick={handleLoginClick}>
            Log in
          </button>
        </div>
      </div>
      <div className={styles.spaceBottom}></div>
      <div className={styles.space}></div>
    </div>
  );
};

export default Intro;
